version: '3.9'

services:
  web:
    build: .
    ports:
      - "3005:8000"     
#    volumes:
#      - .:/app            #Evita tener que reconstruir la imagen por cada cambio.
#    environment:
#      - PYTHONUNBUFFERED=1
#    restart: unless-stopped
