name: Django CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Ejecutar tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Traer Código 
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      #Ejecutar migraciones
      #- name: Run migrations
      # run: python manage.py migrate --no-input
      
      - name: Run tests
        run: python manage.py test --verbosity=2  #Mayor visualización de los Logs
