on:
  issue_comment:
    types: [created]
    
permissions:
  contents: write 

jobs:
  fast-forward:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/ff') }}
    
    steps:
      - name: Fast-forward pull request
        uses: endre-spotlab/fast-forward-pr@v2.1
        with:
          success_message: 'Código propagado correctamente'
          failure_message: 'No se pudo propagar el código'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
